import {
  openUserForm,
  closeUserForm,
  openLoginForm,
  closeLoginForm,
  openAdApprovalNotice,
  closeAdApprovalNotice,
  openSigninForm,
  closeSigninForm,
  openRequestResetPassword,
  closeRequestResetPassword,
  openResetPassword,
  closeResetPassword,
  openMobileFilterAds,
  closeMobileFilterAds,
  openVerifiedEmail,
  closeVerifiedEmail,
  openSessionExpired,
  closeSessionExpired
} from "../reducers/modals.reducers";

export const modalActions = {
  openUserForm,
  closeUserForm,
  openLoginForm,
  closeLoginForm,
  openAdApprovalNotice,
  closeAdApprovalNotice,
  openSigninForm,
  closeSigninForm,
  openRequestResetPassword,
  closeRequestResetPassword,
  openResetPassword,
  closeResetPassword,
  openMobileFilterAds,
  closeMobileFilterAds,
  openVerifiedEmail,
  closeVerifiedEmail,
  openSessionExpired,
  closeSessionExpired
};