name: kiloshare
description: "KiloShare - Application de partage d'espace bagages"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation essentiels pour l'auth
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_screenutil: ^5.9.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # HTTP & API
  dio: ^5.3.4
  http: ^1.2.1
  json_annotation: ^4.8.1
  
  # Internationalization
  intl: ^0.20.2
  
  # Storage sécurisé pour les tokens
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2
  
  # Authentification sociale
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  flutter_dotenv: ^5.1.0
  
  # Image picker et gestion de fichiers pour le profil
  image_picker: ^1.2.0
  file_picker: ^8.1.4
  path: ^1.9.0
  
  # Gestion optimisée des images avec Cloudinary
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  
  # Progress indicators et UI
  percent_indicator: ^4.2.3
  
  # Launcher pour les liens externes
  url_launcher: ^6.2.5
  
  # Package info pour obtenir les infos de l'app
  package_info_plus: ^8.3.1
  bloc: ^8.1.4
  
  # Firebase et notifications
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - .env