name: kiloshare
description: "KiloShare - Application de partage d'espace bagages"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # State Management
  provider: ^6.1.2
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.4
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Authentication & Security
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  local_auth: ^2.1.7
  crypto: ^3.0.3

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1

  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  permission_handler: ^11.1.0
  path: ^1.8.3

  # UI Utilities
  flutter_datetime_picker_plus: ^2.1.0
  country_picker: ^2.0.21
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^8.0.1

  # Payments
  flutter_stripe: ^10.1.1

  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2

  # Utils
  uuid: ^4.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/flags/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700