name: kiloshare
description: "KiloShare - Application de partage d'espace bagages"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation essentiels pour l'auth
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_screenutil: ^5.9.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # HTTP & API
  dio: ^5.3.4
  json_annotation: ^4.8.1
  
  # Storage sécurisé pour les tokens
  flutter_secure_storage: ^9.2.2
  
  # Authentification sociale
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - .env