// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config/environment.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: Environment.firebaseApiKey,
    appId: Environment.firebaseAppId.isEmpty ? '1:${Environment.firebaseSenderId}:web:kiloshare-web' : Environment.firebaseAppId,
    messagingSenderId: Environment.firebaseSenderId,
    projectId: Environment.firebaseProjectId,
    authDomain: '${Environment.firebaseProjectId}.firebaseapp.com',
    storageBucket: '${Environment.firebaseProjectId}.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: Environment.firebaseApiKey,
    appId: Environment.firebaseAppId.isEmpty ? '1:${Environment.firebaseSenderId}:android:abe80a47c7c1fb421537ef' : Environment.firebaseAppId,
    messagingSenderId: Environment.firebaseSenderId,
    projectId: Environment.firebaseProjectId,
    storageBucket: '${Environment.firebaseProjectId}.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: Environment.firebaseApiKey,
    appId: Environment.firebaseAppId.isEmpty ? '1:${Environment.firebaseSenderId}:ios:kiloshare-ios' : Environment.firebaseAppId,
    messagingSenderId: Environment.firebaseSenderId,
    projectId: Environment.firebaseProjectId,
    iosBundleId: 'com.m2atech.kiloshare',
    storageBucket: '${Environment.firebaseProjectId}.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZlgmN3PnUZzQ7YAm1cJzFdnA_example',
    appId: '1:123456789012:macos:abcdef123456789012345',
    messagingSenderId: '123456789012',
    projectId: 'kiloshare-8f7fa',
    storageBucket: 'kiloshare-8f7fa.appspot.com',
    iosBundleId: 'com.kiloshare.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZlgmN3PnUZzQ7YAm1cJzFdnA_example',
    appId: '1:123456789012:windows:abcdef123456789012345',
    messagingSenderId: '123456789012',
    projectId: 'kiloshare-8f7fa',
  );
}