// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAos_M9aCOATa0GXDPqwDqVjSYXQrnb9IY',
    appId: '1:450200476606:web:abe80a47c7c1fb421537ef',
    messagingSenderId: '450200476606',
    projectId: 'kiloshare-8f7fa',
    authDomain: 'kiloshare-8f7fa.firebaseapp.com',
    storageBucket: 'kiloshare-8f7fa.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAos_M9aCOATa0GXDPqwDqVjSYXQrnb9IY',
    appId: '1:450200476606:android:abe80a47c7c1fb421537ef',
    messagingSenderId: '450200476606',
    projectId: 'kiloshare-8f7fa',
    storageBucket: 'kiloshare-8f7fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG1J6SHm9JP5cGPkvigANdCvKjzkvwQtk',
    appId: '1:450200476606:ios:bfb94e1002d559061537ef',
    messagingSenderId: '450200476606',
    projectId: 'kiloshare-8f7fa',
    storageBucket: 'kiloshare-8f7fa.firebasestorage.app',
    iosBundleId: 'com.m2atech.kiloshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOws_DGV7YTnUFPT-VoNGHEL8yG1NOOM',
    appId: '1:450200476606:ios:abe80a47c7c1fb421537ef',
    messagingSenderId: '450200476606',
    projectId: 'kiloshare-8f7fa',
    storageBucket: 'kiloshare-8f7fa.firebasestorage.app',
    iosBundleId: 'com.m2atech.kiloshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAos_M9aCOATa0GXDPqwDqVjSYXQrnb9IY',
    appId: '1:450200476606:web:abe80a47c7c1fb421537ef',
    messagingSenderId: '450200476606',
    projectId: 'kiloshare-8f7fa',
    authDomain: 'kiloshare-8f7fa.firebaseapp.com',
    storageBucket: 'kiloshare-8f7fa.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}